DECLARE @MATRICOLA nvarchar(10) = 
(SELECT TOP 1 CAST(MATRICOLA AS INT) FROM UTENTI ORDER BY MATRICOLA DESC)

SELECT @MATRICOLA AS MATRICOLA FROM UTENTI

SET @MATRICOLA = @MATRICOLA + 1

SELECT @MATRICOLA AS MATRICOLA FROM UTENTI

select * from UTENTI

